CREATE TABLE topico (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    titulo VARCHAR(200) NOT NULL,
    mensagem TEXT NOT NULL,
    data_criacao TIMESTAMP NOT NULL,
    estado VARCHAR(50) NOT NULL,

    autor VARCHAR(150) NOT NULL,
    curso VARCHAR(150) NOT NULL
);
